language: java
jdk:
- openjdk8
script: mvn clean verify

deploy:
  provider: heroku
  api_key:
    secure: q373oSAQPT80egHLAlAvfnMUsad4v0s60Qdu9Tq4iSLYsgpVep1m1EAfcVZKT+qNahpFrkkktSWHna0ZhYyENwELJUFRf6jDMi7oqN3UGN0A16j/rx1D/jkCQP0COf7wp90FaDJwLhVp8jw/SJhSwUvNhzQF+3nPkrdq31lOoCyFWgQh+AsdKoBwqp6IM2SMK/MY5IW0X3qOLav8f2Q9GPxw2PCJrxoysLJCDipa9IUzFTGeQWKHMFRXjLQ12fM1ZNoDAfR0KdbdjKWGZveZPDSLcpOgBitxBNrfiAoCYX4cHyAGaEW0hnlsgKDkoExQFQcf/WnZEMwrn0EmAtj6TaOwIc+AEVWr+/+KAPq/24FPhvyLww2vsFl7tyIwk1ohHHsQFBIzJ8jG8pWKQBdAb2O3fdFu2reFsYt2+1gKgEK0PjWGIOMUykpt8Nvd35enyhpYtqXcBXj1BNnKJRNMnS0+o8jOkuHuljAve/vFZtV3ASrvewhvxEJf5cL8oP4H36ShgbMb3M90S9gmlXa3lwm8fe4c+0UX/U0vJPms/Bf3vlgd4UVd0NwvWegQs1Ybs+IXWzuT79xKis+deAn8Ja4Y6KNmNzn01Op1dxD1a0v+C8EY1ZxzzoedzG8YbgxYSzJ4juAc+nusUsJOyoZeyKqMqSi63pXEZwzJ2tkep1Y=
  app: db-test-project